name: DeployWK
on:
  push:
    branches: [main]

jobs:
  job_only:
    name: teste 02
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ip-198-58-99-223.cloudezapp.io
        username: prauebi
        key_path: /home/prauebi/.ssh/
        key: ${{ secrets.KEY }}
        port: 22122
        script:
          echo "$secrets_KEY"
          cd deploy-folder
          git pull origin master
          git status
