name: DeployWK
on:
  push:
    branches: [main]

jobs:
  job_only:
    name: teste 02
    runs-on: ubuntu-latest
    steps:
    - name: testando os passos do video
      uses: appleboy/ssh-action@master
      with:
        host: ip-198-58-99-223.cloudezapp.io
        username: prauebi
        key: -----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEA9YoIRQLPSGhy7uJzzgIHdCtLBYcb6vhFcIQOdfKdJP/E+1NXMdCYgp0uvwNb23b9apwRJgcxlOMvVZjO5gfQ46MlEbe+P4uU738hw8qGGydQQ9rHQbm4Ecrf3E2KzfE7Ccid8R/ZIZBQV9/P2TGxsA7o7M+six0bU0L6mp3hLSOGbzB1wPU9iZBlj+c0nXWN6ATzggHPQGvVIkw3/pR1xRqFY7sFVQwR5zYCfAYxoHuVdkluXolNfLBflUWo0H4a9ddGbYNb209bp1sw6/jHw9rvk3KLnegedFVUQPWmha67VJ91ap+7SmU2N8eK3zRxqraqYIdHjC7psT0rbvK2jwIDAQABAoIBAQDwVc+KXRmvci0tjhJ0DqBlIQspufmloKW3YEsXQAZ49LFGn2i1pcvh7SCYbx02T930wBY49smdRlJKomvB1NyuND5QfV2GrYV2dyYBkvZ5FZ4HDNoEh1iYcc90v6GhuwFiri+KmPXbWHqLyNKVcYLPJYjwYsYs1Kyubt0FAowptLVOHd/LLY7t469gS17Ypi3PsjcObxhejcEUKgNu0VOWDjazu9VN7JMhTeMB/M66yIt+Y3ROFGkOFTfp+eNt1jBOKE289NpFBZvty7LBbgjcWDfY3bEBC5BSXAdbm83b8xKuuvzr1zGXAe/fOq1T7wmS3ar19Htw02jucdOMDu7BAoGBAPr51POQ1gTPRCMsOS2FUxPItbSFrhA7V9JmqoZOpyoMiZWG9frR4ruhklDH9beh+OmoQIil+BrDzuyuq1J7X/yI9q+oKLLgYjX5yjJLlMQfjnDHH0aVJGHGqEBMpdEqoOxXjeWhh866SQjsmUV74WlgkVJCbdEkmLMIhkzTBBRpAoGBAPp0Vs7KZlg9tidEpw4mXqHQpLOPvNYABn3M+J1c5l/J/ZxR3WFwt3O/k89Ee66Hw5Fj4mpiUNajHSiky7zEyfgIXwyGi4azMFDojS1gviH2UBYTc10s6zE7ssEC+CRwEtemOQYXthCNB/THmlKswMndyp5jei1iXxYB00KL5TQ3AoGAZt1w76dkYLJG3hepE8Q6abhw6R2FWzfHZgAYUlX4Y96hoXygYv4VbQvq+VsLlgk4CSSh1qAX0XiB3jY1F+hjThEg8pv8mlwnRLItsnGR9tRsQEMMyZQlRkHzAe+oYtOTA2tbSEvtasilWJgIthbxK4yd41ZAxmC2iWKsEN7IJEkCgYBpHrlstBD+ynAQzUTcsIgZnMv0PclBfOM8m/JhgiODYvFaUhX8FuY449jzLshGud8AwA7BHiDV5cKQU5Lb2TD4NPNH+5TGZaFK5ECVIjzLXmnAyksqeXcBxA/D6S4jhRKzhqX6g6s8CSWkvL5uIuoMEFZB4njeYaKNRxjXnoYGQwKBgDA2ecmrovHNJMCXu7Er9s22niYJu7Mrt/3dbM+ILyjqISjZaapiQia+w7i15e7GxON/hBxqutV/gm+wNQbd/kYqZYct73lPdySetaFYLx+d3QZBjagM/ySAU1zWviVjlpHAUy4XQGaWlBEJGZAJj2PtmKCSbr7eIaenTGpZLNNa-----END RSA PRIVATE KEY-----
        port: 22122
        script:
          echo ${{ secrets_KEY }}
          cd deploy-folder
          git pull origin master
          git status
