name: DeployWK
on:
  push:
    branches: [main]

jobs:
  job_only:
    name: teste 02
    runs-on: ubuntu-latest
    steps:
    - uses: hengkx/ssh-deploy@v1.0.1
      env:
        HOST: ip-198-58-99-223.cloudezapp.io
        USERNAME: prauebi
        PASSWORD: Adm!@#pr4uebi
        PORT: 22122
        SOURCE: 'dist/'
