name: DeployWK
on:
  push:
    branches: [main]

jobs:
  job_only:
    name: teste 02
    runs-on: ubuntu-latest
    steps:
    - name: SSH Execute Commands
      uses: JimCronqvist/action-ssh@0.1.1
      env:
        NAME: "Root"
      with:
        hosts: 'prauebi@ip-198-58-99-223.cloudezapp.io'
        privateKey: ${{ secrets.DEPLOY_KEY }}
        debug: false
        command: |
          ls -lah
          echo "I am $NAME"
