name: Deploy1

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: conection_server
    steps:
      - name: deploy
        env:
          HOST: ${{ secrets.conection_server.HOST }}
          PORT: ${{ secrets.conection_server.PORT }}
          USER: ${{ secrets.conection_server.USER }}
        run:
          echo $HOST $PORT $USER
        
      
