name: Deploy1

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: conection_server
    steps:
      - name: deploy
        env:
          HOST: asdsa #${{ secrets.HOST_SERVER }}
          PORT: ${{ secrets.PORT_SERVER }}
          USER: ${{ secrets.USER_SERVER }}
        run:
          echo $HOST $PORT $USER
        
      
